version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  labels:
  - govuk-pay
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.4
    - 1.440.5
    - 1.445.0
    - 1.446.0
    - 1.447.0
    - 1.448.0
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.458.0
    - 1.459.0
    - 1.460.0
    - 1.462.0
    - 1.464.0
    - 1.466.0
    - 1.467.0
    - 1.471.0
    - 1.474.0
    - 1.476.0
    - 1.478.0
    - 1.483.0
    - 1.486.0
    - 1.489.0
    - 1.491.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.505.0
    - 1.509.0
    - 1.511.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.532.0
    - 1.538.0
    - 1.541.0
    - 1.557.0
    - 1.564.0
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: node-zendesk
    versions:
    - 2.0.5
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: govuk-frontend
    versions:
    - 3.10.2
  - dependency-name: lodash
    versions:
    - 4.17.20
