language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
env:
  - NODE_ENV: travis
install:
  - npm ci
before_script:
  - npm run compile
deploy:
  provider: cloudfoundry
  api: https://api.cloud.service.gov.uk
  organization: govuk-pay
  space: build
  on:
    repo: alphagov/pay-user-support
